name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.3', '7.4', '8.0' ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - php: '8.1'
            stability: prefer-stable

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - uses: overtrue/phplint@8.0
        with:
          path: src/

      - uses: php-actions/phpunit@v3
