name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: php-actions/composer@v5
      
      - uses: overtrue/phplint@8.0
        with:
          path: src/
      
      - uses: php-actions/phpunit@v3

